from typing import Any, Optional, Dict, List
from datetime import datetime
from dataclasses import dataclass, field

from validation.models.diagnostic_response import DiagnosticResponse
from validation.models.validation_report import ValidationReport, StageResult
from validation.models.validated_response import ValidatedDiagnosticResponse
from validation.evidence_validator import EvidenceValidator
from validation.citation_validator import CitationValidator
from validation.entity_validator import EntityValidator
from validation.relationship_validator import RelationshipValidator
from validation.consistency_checker import ConsistencyChecker
from validation.hallucination_detector import HallucinationDetector
from validation.safety_validator import SafetyValidator
from validation.confidence_engine import ConfidenceEngine
from validation.report_builder import ReportBuilder
from validation.config import ValidationConfig
from validation.validation_context import ValidationContext
from backend.logger import logger

@dataclass
class ValidationResults:
    """Results of the validation pipeline."""
    evidence_results: Any = None
    citation_results: Any = None
    entity_results: Any = None
    relationship_results: Any = None
    consistency_results: Any = None
    hallucination_results: Any = None
    safety_results: Any = None
    confidence_results: Any = None
    validation_report: ValidationReport = field(default_factory=ValidationReport)
    validated_response: ValidatedDiagnosticResponse = field(default_factory=ValidatedDiagnosticResponse)
    processing_time_ms: float = 0.0
    status: str = "PENDING"
    stage_times: Dict[str, float] = field(default_factory=dict)
    stage_errors: Dict[str, str] = field(default_factory=dict)

class ValidationEngine:
    """Grounding & Validation Engine — orchestrates all validation stages.

    Receives a DiagnosticResponse generated by the LLM Orchestration Engine and
    verifies every claim using the retrieved Structured Context Package and the
    engineering knowledge base.

    The engine MUST NEVER generate new engineering knowledge. Its responsibility
    is validation, verification, confidence estimation and safety enforcement.
    """

    STAGES = [
        "EvidenceValidator",
        "CitationValidator",
        "EntityValidator",
        "RelationshipValidator",
        "ConsistencyChecker",
        "HallucinationDetector",
        "SafetyValidator",
        "ConfidenceEngine",
        "ReportBuilder",
    ]

    def __init__(
        self,
        config: Optional[ValidationConfig] = None,
        knowledge_base: Optional[Any] = None,
    ):
        """
        Parameters
        ----------
        config : ValidationConfig, optional
            Configuration for validation (confidence thresholds, safety rules, etc.)
        knowledge_base : Any, optional
            The knowledge base (e.g., database session) containing entity definitions,
            relationships, and citations for validation.
        """
        self.config = config or ValidationConfig()
        self.knowledge_base = knowledge_base

        # Build shared validation context with batched KB access
        self.validation_context = ValidationContext(knowledge_base, self.config)
        entity_cache = self.validation_context.get_entity_cache()
        relationship_cache = self.validation_context.get_relationship_cache()

        # Initialize validators with shared caches and config
        self.evidence_validator = EvidenceValidator()
        self.citation_validator = CitationValidator(self.config)
        self.entity_validator = EntityValidator(knowledge_base, self.config, entity_cache)
        self.relationship_validator = RelationshipValidator(knowledge_base, relationship_cache)
        self.consistency_checker = ConsistencyChecker()
        self.hallucination_detector = HallucinationDetector(knowledge_base, self.config, entity_cache)
        self.safety_validator = SafetyValidator(self.config)
        self.confidence_engine = ConfidenceEngine(self.config)

        # Initialize report builder
        self.report_builder = ReportBuilder(self.config)

    def validate(
        self,
        diagnostic_response: DiagnosticResponse,
        context_package: Any,
    ) -> ValidationResults:
        """Run the complete validation pipeline with stage-level error isolation.

        Each stage executes independently. If one validator fails:

        • the exception is captured
        • the failure is recorded
        • remaining validators continue executing whenever possible

        Parameters
        ----------
        diagnostic_response : DiagnosticResponse
            The LLM-generated diagnostic response to validate.
        context_package : Any
            The Structured Context Package containing supporting evidence.

        Returns
        -------
        ValidationResults
            Complete validation results including report and validated response.
        """
        start_time = datetime.now()
        results = ValidationResults()
        pipeline_stages = []
        completed = []
        failed = []
        stage_errors = {}

        # Initialize validation context cache
        logger.info("validation.pipeline.start", stage_count=len(self.STAGES))
        cache_stats = self.validation_context.get_cache_stats()
        logger.info("validation.cache.initialized",
                    entity_count=cache_stats["entity_count"],
                    relationship_count=cache_stats["relationship_count"])

        # --- Stage 1: Evidence Validation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="EvidenceValidator")
            results.evidence_results = self.evidence_validator.validate(
                diagnostic_response, context_package
            )
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="EvidenceValidator", status="COMPLETED",
                            duration_ms=dur, result_count=len(results.evidence_results.validated_claims))
            )
            completed.append("EvidenceValidator")
            logger.info("validation.stage.complete", stage="EvidenceValidator",
                        duration_ms=dur, claims_validated=len(results.evidence_results.validated_claims))
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="EvidenceValidator", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("EvidenceValidator")
            stage_errors["EvidenceValidator"] = err_msg
            logger.error("validation.stage.failed", stage="EvidenceValidator", error=err_msg)

        # --- Stage 2: Citation Validation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="CitationValidator")
            results.citation_results = self.citation_validator.validate(
                diagnostic_response, context_package
            )
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="CitationValidator", status="COMPLETED",
                            duration_ms=dur, result_count=len(results.citation_results.valid_citations))
            )
            completed.append("CitationValidator")
            logger.info("validation.stage.complete", stage="CitationValidator",
                        duration_ms=dur, citations_valid=len(results.citation_results.valid_citations))
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="CitationValidator", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("CitationValidator")
            stage_errors["CitationValidator"] = err_msg
            logger.error("validation.stage.failed", stage="CitationValidator", error=err_msg)

        # --- Stage 3: Entity Validation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="EntityValidator")
            results.entity_results = self.entity_validator.validate(diagnostic_response)
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="EntityValidator", status="COMPLETED",
                            duration_ms=dur,
                            result_count=len(results.entity_results.validated_entities) +
                                        len(results.entity_results.missing_entities))
            )
            completed.append("EntityValidator")
            logger.info("validation.stage.complete", stage="EntityValidator",
                        duration_ms=dur,
                        entities_validated=len(results.entity_results.validated_entities),
                        entities_missing=len(results.entity_results.missing_entities))
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="EntityValidator", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("EntityValidator")
            stage_errors["EntityValidator"] = err_msg
            logger.error("validation.stage.failed", stage="EntityValidator", error=err_msg)

        # --- Stage 4: Relationship Validation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="RelationshipValidator")
            results.relationship_results = self.relationship_validator.validate(diagnostic_response)
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="RelationshipValidator", status="COMPLETED",
                            duration_ms=dur,
                            result_count=len(results.relationship_results.validated_relationships) +
                                        len(results.relationship_results.failed_relationships))
            )
            completed.append("RelationshipValidator")
            logger.info("validation.stage.complete", stage="RelationshipValidator",
                        duration_ms=dur,
                        relationships_valid=len(results.relationship_results.validated_relationships))
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="RelationshipValidator", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("RelationshipValidator")
            stage_errors["RelationshipValidator"] = err_msg
            logger.error("validation.stage.failed", stage="RelationshipValidator", error=err_msg)

        # --- Stage 5: Consistency Check ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="ConsistencyChecker")
            results.consistency_results = self.consistency_checker.validate(diagnostic_response)
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="ConsistencyChecker", status="COMPLETED",
                            duration_ms=dur,
                            result_count=len(results.consistency_results.issues))
            )
            completed.append("ConsistencyChecker")
            logger.info("validation.stage.complete", stage="ConsistencyChecker",
                        duration_ms=dur, is_consistent=results.consistency_results.is_consistent)
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="ConsistencyChecker", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("ConsistencyChecker")
            stage_errors["ConsistencyChecker"] = err_msg
            logger.error("validation.stage.failed", stage="ConsistencyChecker", error=err_msg)

        # --- Stage 6: Hallucination Detection ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="HallucinationDetector")
            results.hallucination_results = self.hallucination_detector.detect(diagnostic_response)
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="HallucinationDetector", status="COMPLETED",
                            duration_ms=dur,
                            result_count=len(results.hallucination_results.fabricated_items))
            )
            completed.append("HallucinationDetector")
            if results.hallucination_results.has_hallucinations:
                logger.warning("validation.hallucination.detected",
                               count=len(results.hallucination_results.detected_hallucinations))
            logger.info("validation.stage.complete", stage="HallucinationDetector", duration_ms=dur)
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="HallucinationDetector", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("HallucinationDetector")
            stage_errors["HallucinationDetector"] = err_msg
            logger.error("validation.stage.failed", stage="HallucinationDetector", error=err_msg)

        # --- Stage 7: Safety Validation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="SafetyValidator")
            results.safety_results = self.safety_validator.validate(diagnostic_response)
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="SafetyValidator", status="COMPLETED",
                            duration_ms=dur,
                            result_count=len(results.safety_results.triggered_rules))
            )
            completed.append("SafetyValidator")
            if not results.safety_results.is_safe:
                logger.warning("validation.safety.violations",
                               missing_warnings=len(results.safety_results.missing_warnings))
            logger.info("validation.stage.complete", stage="SafetyValidator", duration_ms=dur,
                        is_safe=results.safety_results.is_safe)
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="SafetyValidator", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("SafetyValidator")
            stage_errors["SafetyValidator"] = err_msg
            logger.error("validation.stage.failed", stage="SafetyValidator", error=err_msg)

        # --- Stage 8: Confidence Calculation ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="ConfidenceEngine")
            results.confidence_results = self.confidence_engine.compute(
                results.evidence_results,
                results.citation_results,
                results.entity_results,
                results.relationship_results,
                results.consistency_results,
                results.hallucination_results,
                results.safety_results,
                context_package,
            )
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="ConfidenceEngine", status="COMPLETED",
                            duration_ms=dur, result_count=1)
            )
            completed.append("ConfidenceEngine")
            logger.info("validation.confidence.calculated",
                        overall_score=results.confidence_results.overall_score,
                        confidence_level=results.confidence_results.confidence_level,
                        validation_status=results.confidence_results.validation_status)
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="ConfidenceEngine", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("ConfidenceEngine")
            stage_errors["ConfidenceEngine"] = err_msg
            logger.error("validation.stage.failed", stage="ConfidenceEngine", error=err_msg)

        # --- Stage 9: Report Builder ---
        stage_time = datetime.now()
        try:
            logger.info("validation.stage.start", stage="ReportBuilder")
            building_results = self.report_builder.build_report(
                diagnostic_response,
                results.evidence_results,
                results.citation_results,
                results.entity_results,
                results.relationship_results,
                results.consistency_results,
                results.hallucination_results,
                results.safety_results,
                results.confidence_results,
            )
            results.validation_report = building_results.validation_report
            results.validated_response = building_results.validated_response

            # Enrich the validation report with pipeline execution details
            results.validation_report.pipeline_stages = pipeline_stages
            results.validation_report.completed_stages = completed
            results.validation_report.failed_stages = failed
            results.validation_report.stage_errors = stage_errors
            results.validation_report.config_version = str(self.config.to_dict())
            results.validation_report.safety_rules_triggered = results.safety_results.triggered_rules if results.safety_results else []

            num_hallucinations = len(results.validation_report.hallucination_results)
            results.validation_report.hallucination_summary = (
                f"{num_hallucinations} hallucination(s) detected" if num_hallucinations > 0 else "No hallucinations detected"
            )

            dur = (datetime.now() - stage_time).total_seconds() * 1000
            pipeline_stages.append(
                StageResult(stage_name="ReportBuilder", status="COMPLETED",
                            duration_ms=dur, result_count=1)
            )
            completed.append("ReportBuilder")
            logger.info("validation.stage.complete", stage="ReportBuilder", duration_ms=dur)
        except Exception as e:
            dur = (datetime.now() - stage_time).total_seconds() * 1000
            err_msg = str(e)
            pipeline_stages.append(
                StageResult(stage_name="ReportBuilder", status="FAILED",
                            duration_ms=dur, error=err_msg)
            )
            failed.append("ReportBuilder")
            stage_errors["ReportBuilder"] = err_msg
            logger.error("validation.stage.failed", stage="ReportBuilder", error=err_msg)

        # --- Determine overall status ---
        results.status = self._determine_overall_status(results, failed, stage_errors)

        end_time = datetime.now()
        results.processing_time_ms = (end_time - start_time).total_seconds() * 1000
        results.stage_errors = stage_errors

        # Capture stage times
        for stage in pipeline_stages:
            results.stage_times[stage.stage_name] = stage.duration_ms

        logger.info("validation.pipeline.complete",
                    status=results.status,
                    total_time_ms=results.processing_time_ms,
                    completed_stages=completed,
                    failed_stages=failed)

        return results

    def _determine_overall_status(
        self,
        results: ValidationResults,
        failed_stages: list,
        stage_errors: dict,
    ) -> str:
        """Determine the overall validation status."""
        # Check for critical stage failures
        if failed_stages:
            critical = {"EvidenceValidator", "ConfidenceEngine", "ReportBuilder"}
            if any(s in critical for s in failed_stages):
                return f"ERROR_STAGES_FAILED: {', '.join(failed_stages)}"

        # Check for safety failures
        if hasattr(results, "safety_results") and results.safety_results:
            if not results.safety_results.is_safe:
                return "FAILED_SAFETY"

        # Check for hallucination failures
        if hasattr(results, "hallucination_results") and results.hallucination_results:
            if results.hallucination_results.has_hallucinations:
                return "FAILED_HALLUCINATION"

        # Check confidence engine status
        if hasattr(results, "confidence_results") and results.confidence_results:
            if results.confidence_results.validation_status != "PASSED":
                return results.confidence_results.validation_status

        # Check for warnings
        status = "PASSED"

        if hasattr(results, "hallucination_results") and results.hallucination_results:
            if results.hallucination_results.has_hallucinations:
                status = "WARNING_HALLUCINATION"

        if hasattr(results, "safety_results") and results.safety_results:
            if not results.safety_results.is_safe:
                status = "WARNING_SAFETY"

        # Check for minor issues
        if hasattr(results, "validation_report") and results.validation_report:
            failed_claims = len(results.validation_report.failed_claims)
            missing_entities = len(results.validation_report.missing_entities)
            failed_relationships = len(results.validation_report.failed_relationships)

            if (failed_claims > 0 or missing_entities > 0 or failed_relationships > 0):
                status = "WARNING_ISSUES"

        # Non-critical stage failures
        if failed_stages:
            status = f"WARNING_STAGES: {', '.join(failed_stages)}"

        return status