"""Reusable data models shared by all document processors."""

from processing.models.models import (
    # Existing models (backward compatible)
    Document,
    DocumentMetadata,
    Section,
    Element,
    Chunk,
    Table,
    ImageReference,
    Workbook,
    Worksheet,
    Row,
    Cell,
    DBCMessage,
    DBCSignal,
    DBCNode,
    OCRText,
    BoundingBox,
    # CDS models
    ContentNode,
    Reference,
    Edge,
    RelationshipGraph,
    ProcessingInfo,
    Statistics,
    IDGenerator,
    # Node type constants
    NODE_TYPE_HEADING,
    NODE_TYPE_PARAGRAPH,
    NODE_TYPE_TABLE,
    NODE_TYPE_TABLE_ROW,
    NODE_TYPE_TABLE_CELL,
    NODE_TYPE_WORKSHEET,
    NODE_TYPE_SPREADSHEET_ROW,
    NODE_TYPE_SPREADSHEET_CELL,
    NODE_TYPE_DBC_MESSAGE,
    NODE_TYPE_DBC_SIGNAL,
    NODE_TYPE_IMAGE,
    NODE_TYPE_FIGURE,
    NODE_TYPE_CAPTION,
    NODE_TYPE_OCR_TEXT,
    NODE_TYPE_PROCEDURE,
    NODE_TYPE_WARNING,
    NODE_TYPE_NOTE,
    NODE_TYPE_LIST,
    NODE_TYPE_FORMULA,
    NODE_TYPE_DIAGRAM,
    NODE_TYPE_CODE,
    # Reference type constants
    REF_TYPE_PDF,
    REF_TYPE_EXCEL,
    REF_TYPE_DBC,
    REF_TYPE_IMAGE,
)

__all__ = [
    # Existing
    "Document", "DocumentMetadata", "Section", "Element", "Chunk",
    "Table", "ImageReference", "Workbook", "Worksheet", "Row", "Cell",
    "DBCMessage", "DBCSignal", "DBCNode", "OCRText", "BoundingBox",
    # CDS
    "ContentNode", "Reference", "Edge", "RelationshipGraph",
    "ProcessingInfo", "Statistics", "IDGenerator",
    "NODE_TYPE_HEADING", "NODE_TYPE_PARAGRAPH", "NODE_TYPE_TABLE",
    "NODE_TYPE_TABLE_ROW", "NODE_TYPE_TABLE_CELL",
    "NODE_TYPE_WORKSHEET", "NODE_TYPE_SPREADSHEET_ROW",
    "NODE_TYPE_SPREADSHEET_CELL", "NODE_TYPE_DBC_MESSAGE",
    "NODE_TYPE_DBC_SIGNAL", "NODE_TYPE_IMAGE", "NODE_TYPE_FIGURE",
    "NODE_TYPE_CAPTION", "NODE_TYPE_OCR_TEXT", "NODE_TYPE_PROCEDURE",
    "NODE_TYPE_WARNING", "NODE_TYPE_NOTE", "NODE_TYPE_LIST",
    "NODE_TYPE_FORMULA", "NODE_TYPE_DIAGRAM", "NODE_TYPE_CODE",
    "REF_TYPE_PDF", "REF_TYPE_EXCEL", "REF_TYPE_DBC", "REF_TYPE_IMAGE",
]
