"""Ollama adapter — default LLM runtime for local development.

Communicates with the Ollama HTTP API (``/api/chat`` and ``/api/tags``
endpoints).  Expects Ollama to be installed and the configured model
to be pulled.
"""

import json
import time
from typing import Any, Dict, Generator, Optional

import httpx

from backend.logger import logger
from reasoning.adapters.base_adapter import BaseLLMAdapter, LLMResponse, ModelInfo


class OllamaAdapter(BaseLLMAdapter):
    """Adapter for Ollama's REST API.

    Parameters
    ----------
    model : str
        Ollama model tag (e.g. ``"qwen3:8b"``).
    url : str
        Ollama server URL (default ``http://localhost:11434``).
    temperature : float
        Sampling temperature (0.0 – 2.0).
    top_p : float
        Nucleus sampling parameter.
    max_tokens : int
        Maximum tokens in the completion.
    context_window : int
        Model context window (used for info only).
    timeout_s : int
        HTTP request timeout in seconds.
    """

    def __init__(
        self,
        model: str = "qwen3:8b",
        url: str = "http://localhost:11434",
        temperature: float = 0.1,
        top_p: float = 0.9,
        max_tokens: int = 2048,
        context_window: int = 8192,
        timeout_s: int = 120,
    ) -> None:
        self._model = model
        self._url = url.rstrip("/")
        self._temperature = temperature
        self._top_p = top_p
        self._max_tokens = max_tokens
        self._context_window = context_window
        self._timeout_s = timeout_s
        self._client: Optional[httpx.Client] = None
        self._last_health: Optional[ModelInfo] = None

    # ── BaseLLMAdapter interface ────────────────

    def generate(self, prompt: str, **kwargs: Any) -> LLMResponse:
        start = time.time()
        url = f"{self._url}/api/chat"

        messages = [{"role": "user", "content": prompt}]

        payload: Dict[str, Any] = {
            "model": self._model,
            "messages": messages,
            "options": {
                "temperature": kwargs.get("temperature", self._temperature),
                "top_p": kwargs.get("top_p", self._top_p),
                "num_predict": kwargs.get("max_tokens", self._max_tokens),
            },
            "stream": False,
        }

        # Enable Ollama JSON mode when requested
        if kwargs.get("json_mode", False):
            payload["format"] = "json"

        try:
            client = self._get_client()
            response = client.post(url, json=payload, timeout=self._timeout_s)
            response.raise_for_status()
            data = response.json()

            content = data.get("message", {}).get("content", "")
            elapsed_ms = (time.time() - start) * 1000.0

            prompt_tokens = data.get("prompt_eval_count", 0)
            completion_tokens = data.get("eval_count", 0)

            return LLMResponse(
                text=content.strip(),
                success=True,
                model_used=self._model,
                runtime_used="ollama",
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
                total_tokens=prompt_tokens + completion_tokens,
                generation_time_ms=round(elapsed_ms, 1),
                raw=data,
            )

        except httpx.ConnectError as exc:
            elapsed_ms = (time.time() - start) * 1000.0
            return LLMResponse(
                success=False,
                error=f"Ollama connection failed: {exc}",
                model_used=self._model,
                runtime_used="ollama",
                generation_time_ms=round(elapsed_ms, 1),
            )
        except httpx.HTTPStatusError as exc:
            elapsed_ms = (time.time() - start) * 1000.0
            return LLMResponse(
                success=False,
                error=f"Ollama HTTP {exc.response.status_code}: {exc.response.text[:200]}",
                model_used=self._model,
                runtime_used="ollama",
                generation_time_ms=round(elapsed_ms, 1),
            )
        except Exception as exc:
            elapsed_ms = (time.time() - start) * 1000.0
            return LLMResponse(
                success=False,
                error=f"Ollama error: {exc}",
                model_used=self._model,
                runtime_used="ollama",
                generation_time_ms=round(elapsed_ms, 1),
            )

    def stream_generate(self, prompt: str, **kwargs: Any) -> Generator[str, None, None]:
        """Yield content chunks as they are generated by Ollama."""
        url = f"{self._url}/api/chat"

        messages = [{"role": "user", "content": prompt}]

        payload = {
            "model": self._model,
            "messages": messages,
            "options": {
                "temperature": kwargs.get("temperature", self._temperature),
                "num_predict": kwargs.get("max_tokens", self._max_tokens),
            },
            "stream": True,
        }

        if kwargs.get("json_mode", False):
            payload["format"] = "json"

        client = self._get_client()
        try:
            with client.stream("POST", url, json=payload, timeout=self._timeout_s) as resp:
                for line in resp.iter_lines():
                    if not line:
                        continue
                    try:
                        chunk = json.loads(line)
                        content = chunk.get("message", {}).get("content", "")
                        if content:
                            yield content
                    except (json.JSONDecodeError, KeyError):
                        continue
        except Exception as exc:
            yield f"[Stream error: {exc}]"

    def health_check(self) -> ModelInfo:
        url = f"{self._url}/api/tags"
        try:
            client = self._get_client()
            resp = client.get(url, timeout=10)
            resp.raise_for_status()
            data = resp.json()
            models = data.get("models", [])
            installed = {m.get("name", "") for m in models}

            # Also fetch detailed model info if available
            model_detail: Dict[str, Any] = {}
            for m in models:
                if m.get("name") == self._model:
                    model_detail = {
                        "size": m.get("size", 0),
                        "modified_at": m.get("modified_at", ""),
                        "digest": (m.get("digest") or "")[:12],
                    }
                    break

            if self._model in installed:
                self._last_health = ModelInfo(
                    name=self._model,
                    runtime="ollama",
                    context_window=self._context_window,
                    supports_streaming=True,
                    supports_json_mode=True,
                    healthy=True,
                    details=model_detail,
                )
            else:
                self._last_health = ModelInfo(
                    name=self._model,
                    runtime="ollama",
                    context_window=self._context_window,
                    healthy=False,
                    error=(
                        f"Model '{self._model}' not found in Ollama. "
                        f"Installed: {', '.join(sorted(installed)) or '(none)'}."
                    ),
                )
        except httpx.ConnectError as exc:
            self._last_health = ModelInfo(
                name=self._model,
                runtime="ollama",
                healthy=False,
                error=f"Ollama server is not running at {self._url}. {exc}",
            )
        except Exception as exc:
            self._last_health = ModelInfo(
                name=self._model,
                runtime="ollama",
                healthy=False,
                error=str(exc),
            )
        return self._last_health

    def model_info(self) -> ModelInfo:
        if self._last_health is None:
            return self.health_check()
        return self._last_health

    @property
    def supports_json_mode(self) -> bool:
        return True

    # ── Internal helpers ────────────────────────

    def _get_client(self) -> httpx.Client:
        if self._client is None:
            self._client = httpx.Client(timeout=self._timeout_s)
        return self._client
